version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./faiss_index:/app/faiss_index
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped 